services:
  - type: web
    name: aerofleet-api
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: aerofleet-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.7

databases:
  - name: aerofleet-db
    databaseName: aerofleet
    user: aerofleet
    plan: free
